-- テーブルの作成と初期データの投入。
-- SQL タブで「DB起動」を押したあと、このファイルを開いた状態で「SQL実行」を押す。
-- 一部だけ試したいときは、その範囲を選択してから「SQL実行」を押す。
--
-- HSQLDB はインメモリなので、「DB停止」すると中身は消える。
-- やり直したいときは、もう一度このファイルを流せばよい。

DROP TABLE EMPLOYEE IF EXISTS;
DROP TABLE DEPARTMENT IF EXISTS;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID   INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID     INT,
    EMPLOYEE_NAME   VARCHAR(30) NOT NULL,
    DEPARTMENT_ID   INT,
    SALARY          INT NOT NULL,
    PRIMARY KEY(EMPLOYEE_ID),
    FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

INSERT INTO DEPARTMENT VALUES (1, '営業部');
INSERT INTO DEPARTMENT VALUES (2, '企画部');
INSERT INTO DEPARTMENT VALUES (3, '人事部');

INSERT INTO EMPLOYEE VALUES (10001, 'Alice', 1, 500000);
INSERT INTO EMPLOYEE VALUES (10002, 'Bob',   2, 450000);
INSERT INTO EMPLOYEE VALUES (10003, 'Carol', 3, 350000);
INSERT INTO EMPLOYEE VALUES (10004, 'Dave',  1, 400000);

SELECT * FROM EMPLOYEE ORDER BY EMPLOYEE_ID;
