-- SELECT の基本。1 文ずつ選択して「SQL実行」を押すと結果が見比べやすい。

-- 全件・全カラム
SELECT * FROM EMPLOYEE ORDER BY EMPLOYEE_ID;

-- 必要なカラムだけ取り出す (射影)
SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEE ORDER BY EMPLOYEE_ID;

-- 条件で絞る (選択)
SELECT * FROM EMPLOYEE WHERE SALARY >= 450000 ORDER BY SALARY DESC;

-- 複数条件
SELECT * FROM EMPLOYEE
 WHERE DEPARTMENT_ID = 1
   AND SALARY >= 400000
 ORDER BY EMPLOYEE_ID;

-- 部分一致
SELECT * FROM EMPLOYEE WHERE EMPLOYEE_NAME LIKE 'A%';

-- 並べ替えと件数制限
SELECT EMPLOYEE_NAME, SALARY FROM EMPLOYEE
 ORDER BY SALARY DESC
 LIMIT 2;

-- 列に別名を付ける
SELECT EMPLOYEE_NAME AS 氏名, SALARY / 10000 AS 月給_万円
  FROM EMPLOYEE
 ORDER BY SALARY DESC;
