-- 結合と集約。正規化したテーブルを、必要な形に戻して読むための道具。

-- 内部結合: 両方のテーブルに対応する行があるものだけ
SELECT E.EMPLOYEE_NAME, D.DEPARTMENT_NAME, E.SALARY
  FROM EMPLOYEE E
  JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 ORDER BY E.EMPLOYEE_ID;

-- 外部結合: 社員が 1 人もいない部署も残す
SELECT D.DEPARTMENT_NAME, E.EMPLOYEE_NAME
  FROM DEPARTMENT D
  LEFT JOIN EMPLOYEE E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 ORDER BY D.DEPARTMENT_ID, E.EMPLOYEE_ID;

-- 集約関数
SELECT COUNT(*) AS 人数, SUM(SALARY) AS 合計, AVG(SALARY) AS 平均,
       MIN(SALARY) AS 最小, MAX(SALARY) AS 最大
  FROM EMPLOYEE;

-- グループごとの集約
SELECT D.DEPARTMENT_NAME, COUNT(*) AS 人数, AVG(E.SALARY) AS 平均給与
  FROM EMPLOYEE E
  JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME
 ORDER BY 平均給与 DESC;

-- グループを絞る (WHERE は行を絞り、HAVING はグループを絞る)
SELECT D.DEPARTMENT_NAME, COUNT(*) AS 人数
  FROM EMPLOYEE E
  JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(*) >= 2;

-- サブクエリ: 平均より給与が高い社員
SELECT EMPLOYEE_NAME, SALARY
  FROM EMPLOYEE
 WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE)
 ORDER BY SALARY DESC;
