-- サブクエリとビュー。01_setup.sql を流したあとに実行する。
--
-- サブクエリは「SQL の中に埋め込んだ別の SQL」である。
-- 内側の検索結果を、外側の条件やデータ源として使う。

-- ── WHERE 句のサブクエリ（1 つの値を返す）──────────────
-- 平均より月給が高い社員。内側が先に平均を出し、外側がそれと比べる
SELECT EMPLOYEE_NAME, SALARY
  FROM EMPLOYEE
 WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE)
 ORDER BY SALARY DESC;

-- ── WHERE 句のサブクエリ（複数の値を返す）──────────────
-- 新宿支社にある部署の社員。内側が部署 ID の一覧を返し、外側が IN で受ける
SELECT EMPLOYEE_NAME, DEPARTMENT_ID
  FROM EMPLOYEE
 WHERE DEPARTMENT_ID IN (
           SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE LOCATION = '新宿支社'
       )
 ORDER BY EMPLOYEE_ID;

-- 同じ結果は結合でも書ける。読みやすいほうを選べばよい
SELECT E.EMPLOYEE_NAME, E.DEPARTMENT_ID
  FROM EMPLOYEE E
 INNER JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE D.LOCATION = '新宿支社'
 ORDER BY E.EMPLOYEE_ID;

-- ── SELECT 句のサブクエリ ───────────────────────────
-- 1 行ごとに内側を実行して、値を 1 つ持ってくる
SELECT E.EMPLOYEE_NAME,
       (SELECT D.DEPARTMENT_NAME
          FROM DEPARTMENT D
         WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) AS DEPT_NAME
  FROM EMPLOYEE E
 ORDER BY E.EMPLOYEE_ID;

-- ── FROM 句のサブクエリ ─────────────────────────────
-- 集計した結果を、あらためてテーブルのように扱う
SELECT S.DEPARTMENT_ID, S.人数
  FROM (SELECT DEPARTMENT_ID, COUNT(*) AS 人数
          FROM EMPLOYEE
         GROUP BY DEPARTMENT_ID) S
 WHERE 2 <= S.人数;

-- ── EXISTS: 対応する行があるか ──────────────────────
-- 社員が 1 人以上いる部署だけを出す
SELECT D.DEPARTMENT_NAME
  FROM DEPARTMENT D
 WHERE EXISTS (SELECT 1 FROM EMPLOYEE E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
 ORDER BY D.DEPARTMENT_ID;

-- NOT EXISTS なら、社員が 1 人もいない部署（監査室）だけが残る
SELECT D.DEPARTMENT_NAME
  FROM DEPARTMENT D
 WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEE E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
 ORDER BY D.DEPARTMENT_ID;

-- ── ビュー: SELECT 文に名前を付けて使い回す ───────────
-- ビューは実際のデータを持たない（参照するたびに、元の SELECT が実行される）
DROP VIEW HIGH_SALARY_EMPLOYEES IF EXISTS;

CREATE VIEW HIGH_SALARY_EMPLOYEES AS
SELECT E.EMPLOYEE_NAME, E.SALARY, D.DEPARTMENT_NAME
  FROM EMPLOYEE E
 INNER JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE 400000 <= E.SALARY;

-- テーブルと同じように検索できる
SELECT * FROM HIGH_SALARY_EMPLOYEES ORDER BY SALARY DESC;

-- 元のデータを変えると、ビューの結果も変わる
UPDATE EMPLOYEE SET SALARY = 390000 WHERE EMPLOYEE_NAME = 'Dave';

SELECT * FROM HIGH_SALARY_EMPLOYEES ORDER BY SALARY DESC;
