-- この演習の初期状態（テーブルの作り直しと初期データ）
--
-- 「実行」で SQL ファイルを流すと、Codinable が毎回その前にこのファイルを自動で流す
-- そのため、どのファイルも何度でも「初期データから」実行できる
-- （更新系の SQL を 2 回流して主キーが重複する、ということが起きない）
--
-- 範囲を選択して「実行」したときは流さない（1 文ずつ順に試せるように）
-- このファイルを自分で直すと、初期状態もそのとおりに変わる

DROP TABLE EMPLOYEE IF EXISTS CASCADE;
DROP TABLE DEPARTMENT IF EXISTS CASCADE;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID   INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL,
    LOCATION        VARCHAR(30) NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID   INT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(30) NOT NULL,
    DEPARTMENT_ID INT,
    ENTRANCE_DATE DATE NOT NULL,
    SALARY        INT  NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

INSERT INTO DEPARTMENT VALUES (1, '営業部', '本社');
INSERT INTO DEPARTMENT VALUES (2, '企画部', '本社');
INSERT INTO DEPARTMENT VALUES (3, '人事部', '新宿支社');
INSERT INTO DEPARTMENT VALUES (4, '監査室', '新宿支社');

INSERT INTO EMPLOYEE VALUES (10001, 'Alice', 1, DATE '2018-04-01', 500000);
INSERT INTO EMPLOYEE VALUES (10002, 'Bob',   2, DATE '2019-04-01', 450000);
INSERT INTO EMPLOYEE VALUES (10003, 'Carol', 3, DATE '2020-10-01', 350000);
INSERT INTO EMPLOYEE VALUES (10004, 'Dave',  1, DATE '2021-04-01', 400000);
INSERT INTO EMPLOYEE VALUES (10005, 'Eve', NULL, DATE '2026-04-01', 300000);
