-- この演習の初期状態（テーブルの作り直しと初期データ）
--
-- 「実行」で SQL ファイルを流すと、Codinable が毎回その前にこのファイルを自動で流す
-- そのため、どのファイルも何度でも「初期データから」実行できる
-- （更新系の SQL を 2 回流して主キーが重複する、ということが起きない）
--
-- 範囲を選択して「実行」したときは流さない（1 文ずつ順に試せるように）
-- このファイルを自分で直すと、初期状態もそのとおりに変わる

DROP TABLE PRODUCT IF EXISTS CASCADE;

CREATE TABLE PRODUCT (
    PRODUCT_ID   INT         PRIMARY KEY,
    PRODUCT_NAME VARCHAR(40) NOT NULL,
    PRODUCT_CODE CHAR(8)     UNIQUE,
    PRICE        DECIMAL(10, 2) NOT NULL,
    STOCK        INT         DEFAULT 0 NOT NULL,
    RATING       INT         CHECK (RATING BETWEEN 1 AND 5),
    AVAILABLE    BOOLEAN     DEFAULT TRUE NOT NULL,
    RELEASE_DATE DATE,
    CREATED_AT   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, PRICE, STOCK, RATING, RELEASE_DATE)
VALUES (1, 'ノート', 'NB-00001', 480.00, 120, 4, DATE '2025-04-01');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, PRICE, STOCK, RATING, RELEASE_DATE)
VALUES (2, '万年筆', 'FP-00001', 3200.50, 8, 5, DATE '2025-06-15');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, PRICE)
VALUES (3, 'インク', 'IK-00001', 1100.00);
