plugins { id 'application' }

repositories { mavenCentral() }
java { sourceCompatibility = '25'; targetCompatibility = '25' }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

dependencies {
    implementation 'com.rabbitmq:amqp-client:5.36.0'
    runtimeOnly 'org.slf4j:slf4j-simple:2.0.17'
}

application { mainClass = 'RabbitExample' }
