server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 開発中はテンプレートを読み直したいのでキャッシュを切る
    cache: false
    servlet:
      content-type: text/html
