-- sql/hsqldb/3_EMPLOYEE_DML.sql と同じ内容（Codinable では起動時に spring.sql.init で流す）
-- 2 回目以降の起動では主キーの重複で失敗するが、continue-on-error で読み飛ばす
-- （登録・更新した社員を再起動で消さないため）

INSERT INTO DEPARTMENT VALUES (1, '営業部', '東京');
INSERT INTO DEPARTMENT VALUES (2, '開発部', '大阪');
INSERT INTO DEPARTMENT VALUES (3, '人事部', '東京');
INSERT INTO DEPARTMENT VALUES (4, '総務部', '福岡');

INSERT INTO JOB VALUES (1, '一般', 1);
INSERT INTO JOB VALUES (2, '主任', 2);
INSERT INTO JOB VALUES (3, '課長', 3);
INSERT INTO JOB VALUES (4, '部長', 4);
INSERT INTO JOB VALUES (5, '本部長', 5);

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (1, 'E0001', '山田 太郎', 1, 3, 520000, DATE '2012-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (2, 'E0002', '佐藤 花子', 2, 4, 680000, DATE '2010-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (3, 'E0003', '鈴木 一郎', 3, 1, 300000, DATE '2019-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (4, 'E0004', '高橋 美咲', 4, 2, 380000, DATE '2017-10-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (5, 'E0005', '田中 健太', 1, 1, 280000, DATE '2021-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (6, 'E0006', '伊藤 由美', 2, 2, 450000, DATE '2016-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (7, 'E0007', '渡辺 翔', 2, 1, 320000, DATE '2020-10-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (8, 'E0008', '中村 彩', 3, 3, 500000, DATE '2014-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (9, 'E0009', '小林 大輔', 1, 5, 700000, DATE '2008-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, DEPARTMENT_ID,
  JOB_ID, SALARY, ENTRANCE_DATE) VALUES
  (10, 'E0010', '加藤 直樹', 4, 1, 250000, DATE '2023-04-01');

ALTER TABLE EMPLOYEE ALTER COLUMN EMPLOYEE_ID RESTART WITH 11;
