-- 部署テーブル
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION) VALUES(10, '営業部', '東京');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION) VALUES(20, '開発部', '大阪');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION) VALUES(30, '総務部', '東京');

-- 社員テーブル
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, JOB_NAME, SALARY, ENTRANCE_DATE) VALUES(1, 'Alice', 10, 'Sales', 300000, '2018-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, JOB_NAME, SALARY, ENTRANCE_DATE) VALUES(2, 'Bob', 20, 'Engineer', 350000, '2015-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, JOB_NAME, SALARY, ENTRANCE_DATE) VALUES(3, 'Carol', 20, 'Engineer', 400000, '2012-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, JOB_NAME, SALARY, ENTRANCE_DATE) VALUES(4, 'Dave', 10, 'Manager', 450000, '2008-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, JOB_NAME, SALARY, ENTRANCE_DATE) VALUES(5, 'Ellen', 30, 'Clerk', 250000, '2020-04-01');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, JOB_NAME, SALARY, ENTRANCE_DATE) VALUES(6, 'Frank', 30, 'Manager', 420000, '2010-04-01');
ALTER TABLE EMPLOYEE ALTER COLUMN EMPLOYEE_ID RESTART WITH 7;
