-- 部署テーブル
CREATE TABLE DEPARTMENT (
DEPARTMENT_ID   INTEGER PRIMARY KEY,           -- 部署ID
DEPARTMENT_NAME VARCHAR(30) NOT NULL,          -- 部署名
LOCATION        VARCHAR(30)                    -- 所在地
);

-- 社員テーブル
CREATE TABLE EMPLOYEE (
EMPLOYEE_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 社員ID
EMPLOYEE_NAME VARCHAR(30) NOT NULL,            -- 社員名
DEPARTMENT_ID INTEGER NOT NULL,                -- 部署ID（外部キー）
JOB_NAME      VARCHAR(20),                     -- 職種
SALARY        INTEGER,                         -- 給与
ENTRANCE_DATE     DATE,                            -- 入社日
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID)
);
